### ISSUE TITLE
What does the distance=-1 means？

### ISSUE THREAD

**Issue by vba34520** [arunmandal53/facematch#9]
I matched a close picture and a far picture of me.
The match result is distance = -1.
I guess the far one can't not detect the face.
Looking forward to your reply ! Thanks.

**Comment by arunmandal53** [comment]
face is not detected so returned -1.

**Comment by vba34520** [comment]
Thank you very much. So I think it's more reasonable that the print of `face_match_demo.py` change into `print("Result = " + ("same person" if (distance <= threshold and distance != -1) else "different person"))`
